onrails/fx1/config/routes.rb
Fx1::Application.routes.draw do
  get "users/new"
  namespace :admin do
    resources :archive_links
  end

  namespace :admin do
    resources :xampp_versions
  end

  root 'mainpage#index'

end

onrails/fx1/app/models/admin/xampp_version.rb
class Admin::XamppVersion < ActiveRecord::Base
  has_many :archive_links
  PRODUCT_VERSION_VALID = /\A[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(\-[0-9]{1,3})?\z/
  validates :xampp_version, presence: true, format: {with: PRODUCT_VERSION_VALID}
  validates :apache_version, presence: true, format: {with: PRODUCT_VERSION_VALID}
  validates :php_version, presence: true, format: {with: PRODUCT_VERSION_VALID}
  validates :mysql_client_version, presence: true, format: {with: PRODUCT_VERSION_VALID}
  validates :mysql_server_version, presence: true, format: {with: PRODUCT_VERSION_VALID}
end

onrails/fx1/app/models/xampp_version.rb
class XamppVersion < ActiveRecord::Base
end

onrails/fx1/app/controllers/admin/xampp_versions_controller.rb
class Admin::XamppVersionsController < ApplicationController
  layout 'admin'
  before_action :set_admin_xampp_version, only: [:show, :edit, :update, :destroy]

  # GET /admin/xampp_versions
  # GET /admin/xampp_versions.json
  def index
    @admin_xampp_versions = Admin::XamppVersion.all
  end

  # GET /admin/xampp_versions/1
  # GET /admin/xampp_versions/1.json
  def show
  end

  # GET /admin/xampp_versions/new
  def new
    @admin_xampp_version = Admin::XamppVersion.new
  end

  # GET /admin/xampp_versions/1/edit
  def edit
  end

  # POST /admin/xampp_versions
  # POST /admin/xampp_versions.json
  def create
    @admin_xampp_version = Admin::XamppVersion.new(admin_xampp_version_params)

    respond_to do |format|
      if @admin_xampp_version.save
        if !rewrite_links(@admin_xampp_version.id)
          @errors = @archive_links_errors
          format.js {render action: 'create'}
          format.html { render action: 'edit' }
          format.json { render json: @admin_xampp_version.errors, status: :unprocessable_entity }
        end
        format.js { render action: 'create' }
        format.html { redirect_to @admin_xampp_version, notice: 'Xampp version was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_xampp_version }
      else
        @errors = @admin_xampp_version.errors
        format.js {render action: 'create'}
        format.html { render action: 'new' }
        format.json { render json: @admin_xampp_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/xampp_versions/1
  # PATCH/PUT /admin/xampp_versions/1.json
  def update
    respond_to do |format|
      if @admin_xampp_version.update(admin_xampp_version_params)
        if !rewrite_links(@admin_xampp_version.id)
          @errors = @archive_links_errors
          format.js {render action: 'update'}
          format.html { render action: 'edit' }
          format.json { render json: @admin_xampp_version.errors, status: :unprocessable_entity }
        end
        format.js { render action: 'update' }
        format.html { redirect_to @admin_xampp_version, notice: 'Xampp version was successfully updated.' }
        format.json { head :no_content }
      else
        @errors = @admin_xampp_version.errors
        format.js {render action: 'update'}
        format.html { render action: 'edit' }
        format.json { render json: @admin_xampp_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/xampp_versions/1
  # DELETE /admin/xampp_versions/1.json
  def destroy
    @admin_xampp_version.destroy
    respond_to do |format|
      format.html { redirect_to admin_xampp_versions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_xampp_version
      @admin_xampp_version = Admin::XamppVersion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_xampp_version_params
      params.require(:admin_xampp_version).permit(:apache_version, :mysql_client_version, :mysql_server_version, :php_version, :xampp_version)
    end
    
    # Save xampp versions link
    def rewrite_links(xampp_version_id)
      Admin::ArchiveLink.delete_all("xampp_version_id = #{xampp_version_id}")
      links = params[:admin_archive_link][:alink]
      links.each do |index, l|
        link = Admin::ArchiveLink.new(l)
        link.xampp_version_id = xampp_version_id
        if !link.save
          @archive_links_errors = link.errors
          return false
        end
      end
      return true
    end
end

onrails/fx1/app/helpers/admin/xampp_versions_helper.rb
module Admin::XamppVersionsHelper
  def prepareErrors(errList)
    s = ''
    keys = []
    @errors.each do |k, v|
	  ctrl = keys.find {|n| n == k}
	  if ctrl == nil
	    s += t(:Field) + ' ' +  t(k) + ' ' + v + "\n"
	    keys.push k
	  end
    end
    return s
  end
end

onrails/fx1/app/views/admin/xampp_versions/_edit.html.erb
Ya forma

onrails/fx1/app/views/admin/xampp_versions/_form.html.erb
<%= form_for(@admin_xampp_version, remote:true) do |f| %>
  <% if @admin_xampp_version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_xampp_version.errors.count, "error") %> prohibited this admin_xampp_version from being saved:</h2>

      <ul>
      <% @admin_xampp_version.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:xampp_version) %>
    <%= f.text_field :xampp_version %>
  </div>
  <div class="field">
    <%= f.label t(:apache_version) %>
    <%= f.text_field :apache_version %>
  </div>
  <div class="field">
    <%= f.label t(:php_version) %>
    <%= f.text_field :php_version %>
  </div>
  <div class="field">
    <%= f.label t(:mysql_client_version) %>
    <%= f.text_field :mysql_client_version %>
  </div>
  <div class="field">
    <%= f.label t(:mysql_server_version) %>
    <%= f.text_field :mysql_server_version %>
  </div>
  
  <% @cnt = 0 %>
  <%=render :partial => 'version_link', :collection => @admin_xampp_version.archive_links %>

  <% while @cnt < 2 %>
    <%=render :partial => 'version_link', :object => 0 %>
  <% end %>
  
  <div class="actions">
    <%= f.submit(:class => 'ajax_sub')%>
  </div>
<% end %>

onrails/fx1/app/views/admin/xampp_versions/_list_item.html.erb
<tr id="xv-<%=list_item.id%>">
        <td><%= list_item.xampp_version %></td>
        <td><%= list_item.apache_version %></td>
        <td><%= list_item.php_version %></td>
        <td><%= list_item.mysql_server_version %></td>
        <td><%= list_item.mysql_client_version %></td>
        
        <td><%= link_to 'Show', list_item %></td>
        <td>
			<%=form_tag({:action => :edit, :id => list_item}, remote: true, method: :get) do%>
			<%=submit_tag t(:edit), :class=>'ajax_sub' %>
			<% end %>
        </td>
        <td><%= link_to 'Destroy', list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

onrails/fx1/app/views/admin/xampp_versions/_version_link.html.erb
<% 
   bits = ''
   link_full = ''
   link_light = ''
   if (version_link != 0)
     bits = version_link.bits
     link_full = version_link.link_full
     link_light = version_link.link_light
   end
%>

	<fieldset class="set">
		<div class="field">
			<label><%=t(:bits)%></label><br>
			<%=text_field_tag "admin_archive_link_alink_#{@cnt}_bits", bits, {:name => "admin_archive_link[alink][#{@cnt}][bits]"} %><br>
			<label><%=t(:link_full)%></label><br>
			<%=text_field_tag "admin_archive_link_alink_#{@cnt}_link__full", link_full, {:name => "admin_archive_link[alink][#{@cnt}][link_full]"} %><br>
			<label><%=t(:link_light)%></label><br>
			<%=text_field_tag "admin_archive_link_alink_#{@cnt}_link__light", link_light, {:name => "admin_archive_link[alink][#{@cnt}][link_light]"} %><br>
			<% @cnt = @cnt + 1 %>
		</div>
	</fieldset>

onrails/fx1/app/views/admin/xampp_versions/create.js.erb
<%
if @errors
  s = prepareErrors(@errors)
  %>
    adminApp.alert('<%=escape_javascript(s)%>');
    hideLoader();
  <%
else
%>
	<%
	  tr = render(:partial => 'list_item', :object => @admin_xampp_version)
	%>
	var html = '<%=escape_javascript(tr)%>';
	$("#versionList").append(html);
	onReady();
	appWindowClose();
	hideLoader();
<% end %>

onrails/fx1/app/views/admin/xampp_versions/edit.html.erb
<h1>Editing admin_xampp_version</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_xampp_version %> |
<%= link_to 'Back', admin_xampp_versions_path %>

onrails/fx1/app/views/admin/xampp_versions/edit.js.erb
<%
  html = render(:partial => 'form', :object => @admin_xampp_version)
  html = escape_javascript(html)
%>
$('#edit_form_place').html('<%=html%>');
onReady();
appWindow("edit_form_place", '<%=t(:xampp_version)%>', null);
//configureTinyMCE();
hideLoader();

onrails/fx1/app/views/admin/xampp_versions/index.html.erb
<h1>Listing admin_xampp_versions</h1>

<table id="versionList">
  <thead>
    <tr>
      <th><%=t(:xampp_version) %></th>
      <th><%=t(:apache_version) %></th>
      <th><%=t(:php_version) %></th>
      <th><%=t(:mysql_server_version) %></th>
      <th><%=t(:mysql_client_version) %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      <%=render partial: 'list_item', :collection => @admin_xampp_versions %>
  </tbody>
</table>

<br>

<%= form_tag({:action => :new, :id => @admin_xampp_version }, remote:true, :method => :get) do%>
<%=submit_tag(:new_xampp_version, :class=>'ajax_sub') %>
<% end %>
<div id="edit_form_place"></div>

onrails/fx1/app/views/admin/xampp_versions/new.html.erb
<h1>New admin_xampp_version</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_xampp_versions_path %>

onrails/fx1/app/views/admin/xampp_versions/new.js.erb
<%
  form = render(:partial => 'form', :object => @admin_xampp_version)
%>
$('#edit_form_place').html('<%=escape_javascript(form)%>');
appWindow("edit_form_place", '<%=t(:xampp_version)%>', null);
onReady();
hideLoader();

onrails/fx1/app/views/admin/xampp_versions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_xampp_version_path(@admin_xampp_version) %> |
<%= link_to 'Back', admin_xampp_versions_path %>

onrails/fx1/app/views/admin/xampp_versions/update.js.erb
<%
if @errors
  s = prepareErrors(@errors)
  %>
    adminApp.alert('<%=escape_javascript(s)%>');
    hideLoader();
  <%
else
%>
	<%
	  tr = render(:partial => 'list_item', :object => @admin_xampp_version)
	%>
	var html = '<%=escape_javascript(tr)%>';
	$("#xv-<%=@admin_xampp_version.id%>").replaceWith(html);
	onReady();
	appWindowClose();
	hideLoader();
	
<% end %>