onrails/fx1/config/routes.rb
Fx1::Application.routes.draw do
  get "users/new"
  namespace :admin do
    resources :archive_links
  end

  namespace :admin do
    resources :xampp_versions
  end

  root 'mainpage#index'

end

onrails/fx1/app/models/admin/archive_link.rb
class Admin::ArchiveLink < ActiveRecord::Base
  has_one :xampp_version
  NUMBER = /\A[^0]{1}[0-9]{1,3}\z/
  validates :bits, presence:true, format: {with: NUMBER}
end

onrails/fx1/app/controllers/admin/archive_links_controller.rb
class Admin::ArchiveLinksController < ApplicationController
  layout 'admin'
  before_action :set_admin_archive_link, only: [:show, :edit, :update, :destroy]

  # GET /admin/archive_links
  # GET /admin/archive_links.json
  def index
    @admin_archive_links = Admin::ArchiveLink.all
  end

  # GET /admin/archive_links/1
  # GET /admin/archive_links/1.json
  def show
  end

  # GET /admin/archive_links/new
  def new
    @admin_archive_link = Admin::ArchiveLink.new
  end

  # GET /admin/archive_links/1/edit
  def edit
  end

  # POST /admin/archive_links
  # POST /admin/archive_links.json
  def create
    @admin_archive_link = Admin::ArchiveLink.new(admin_archive_link_params)

    respond_to do |format|
      if @admin_archive_link.save
        format.html { redirect_to @admin_archive_link, notice: 'Archive link was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_archive_link }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_archive_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/archive_links/1
  # PATCH/PUT /admin/archive_links/1.json
  def update
    respond_to do |format|
      if @admin_archive_link.update(admin_archive_link_params)
        format.html { redirect_to @admin_archive_link, notice: 'Archive link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_archive_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/archive_links/1
  # DELETE /admin/archive_links/1.json
  def destroy
    @admin_archive_link.destroy
    respond_to do |format|
      format.html { redirect_to admin_archive_links_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_archive_link
      @admin_archive_link = Admin::ArchiveLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_archive_link_params
      params.require(:admin_archive_link).permit(:bits, :link_full, :link_light, :xampp_version_id)
    end
end

onrails/fx1/app/helpers/admin/archive_links_helper.rb
module Admin::ArchiveLinksHelper
end

onrails/fx1/app/views/admin/archive_links/_form.html.erb
<%= form_for(@admin_archive_link) do |f| %>
  <% if @admin_archive_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_archive_link.errors.count, "error") %> prohibited this admin_archive_link from being saved:</h2>

      <ul>
      <% @admin_archive_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:xampp_version) %><br>
    <%= f.select :xampp_version_id, Admin::XamppVersion.all.collect {|p| [p.xampp_version, p.id]} %>
  </div>

  <div class="field">
    <%= f.label :bits %><br>
    <%= f.number_field :bits %>
  </div>
  <div class="field">
    <%= f.label :link_full %><br>
    <%= f.text_field :link_full %>
  </div>
  <div class="field">
    <%= f.label :link_light %><br>
    <%= f.text_field :link_light %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

onrails/fx1/app/views/admin/archive_links/edit.html.erb
<h1>Editing admin_archive_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_archive_link %> |
<%= link_to 'Back', admin_archive_links_path %>

onrails/fx1/app/views/admin/archive_links/index.html.erb
<h1>Listing admin_archive_links</h1>

<table>
  <thead>
    <tr>
      <th>Bits</th>
      <th>Link full</th>
      <th>Link light</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_archive_links.each do |admin_archive_link| %>
      <tr>
        <td><%= admin_archive_link.bits %></td>
        <td><%= admin_archive_link.link_full %></td>
        <td><%= admin_archive_link.link_light %></td>
        <td><%= link_to 'Show', admin_archive_link %></td>
        <td><%= link_to 'Edit', edit_admin_archive_link_path(admin_archive_link) %></td>
        <td><%= link_to 'Destroy', admin_archive_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Archive link', new_admin_archive_link_path %>

onrails/fx1/app/views/admin/archive_links/new.html.erb
<h1>New admin_archive_link</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_archive_links_path %>

onrails/fx1/app/views/admin/archive_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bits:</strong>
  <%= @admin_archive_link.bits %>
</p>

<p>
  <strong>Link full:</strong>
  <%= @admin_archive_link.link_full %>
</p>

<p>
  <strong>Link light:</strong>
  <%= @admin_archive_link.link_light %>
</p>

<%= link_to 'Edit', edit_admin_archive_link_path(@admin_archive_link) %> |
<%= link_to 'Back', admin_archive_links_path %>